### ISSUE TITLE
Closing does not update the status

### ISSUE THREAD

**Issue by sammymat** [knstntn1/homebridge-mqtt-blinds#1]
Firstly, thanks for a great plugin, but when closing the blind, the spinning/loading icon does not stop even if I update send 2 to myBlind/GET/positionState, any idea what could be causing this?

**Comment by sammymat** [comment]
not an issue, sorry, all I had to do was to update the currentPosition to be the same as the targetPosition when the action is completed, works like a charm ;-)

**Comment by faltim** [comment]
Im not sure in which cases HomeKit needs the positionState. In my case it is absolutely the same you wrote above. When I set a new target position in HomeKit the plugin sends out the value via MQTT. When my blind reaches the target position it sends out the same position value as the current one and the spinnig/loading icon stops. However the positionState works as well. You can take a look in the log while controlling your blind. :)
