### ISSUE TITLE
Different positionState values

### ISSUE THREAD

**Issue by Kepete** [knstntn1/homebridge-mqtt-blinds#3]
Thanks for the plugin!
For my use-case I would need to change the positionState values so that 
0 will stop the curtain
-1 will open the curtain. Requires (0) to stop the motor
1 will close the curtain. Requires (0) to stop the motor
https://github.com/nidayand/motor-on-roller-blind-ws

It should be an easy change but I didn't figure it out... 

And I read on another issue that you had a plan to post a tutorial or a description of what you did with your curtains, is this already posted somewhere? :)

**Comment by faltim** [comment]
The change should be easy. I don't use the plugin anymore and for now i don't have time to implement this feature. I will try to implement it till the end of October.

Because of missing time, my blinds are still work in progress.

**Comment by Kepete** [comment]
Totally understand. I'm also missing time and blinds progress slowly.
October seems allright :)

**Comment by knstntn1** [comment]
Hi, i've implemented configurable positionState values. As HomeKit doesn't use the positionState values, but only target und current position for calculation, i also added some logic therefore.
https://github.com/knstntn1/homebridge-mqtt-blinds
Maybe we can add this to your master. If you will not use or develop this plugin any more, just say so.

**Comment by faltim** [comment]
I don't use homebridge anymore. It would be better if you can go on with the development of the plugin. I will delete this repo in a few days. I think that the fork from @knstntn1 will be the new parent repo and the development can go on. Is that okay?

**Comment by knstntn1** [comment]
I think it would be better, if you could pass the ownership (https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account), which keeps the history (issues etc.).
i will afterwards transfer my changes and delete my fork

**Comment by faltim** [comment]
@Kepete It doesn't work. I got the following error message from Github: 

> knstntn1 already has a repository in the bonze4/homebridge-mqtt-blinds network

I think you have to delete your fork. Otherwise its not possible to transfer this repo to you.

**Comment by knstntn1** [comment]
Ok, i‘ve deleted my fork

**Comment by faltim** [comment]
I did the transfer to you @knstntn1

**Comment by knstntn1** [comment]
configurable positionStateValues added in v.1.0.5
