### ISSUE TITLE
Problems with Shelly 2 on 1.4.4?

### ISSUE THREAD

**Issue by rpolenthon** [knstntn1/homebridge-mqtt-blinds#4]
Hi,
I used your plugin the first time from the fork. I had a shelly 2 on 1.4.3 with no problems at all.
My new shelly 2 for another window is on 1.4.4 and I have very annoying problems. If I say Siri to turn the blades on 50% there is only the cycle animation in the Home App. It needs a long time until the percent is showing up. I saw you had a new version, so I tried it and activated also manualControls in the config. But still it doesn't work as it should. Also manual changes are not working well. There is a big time delay or there are wrong animations. 

Do you have problems with your Shellys as well? 

I can't test the shelly with 1.4.3, because I can't use these blades belong to the weather conditions.

Greetings from Germany.

**Comment by knstntn1** [comment]
Hi,

for me it‘s working with 1.4.4.
Can you show the logging and, if possible, the mqtt traffic ?

**Comment by rpolenthon** [comment]
Schnell mal auf deutsch, da soweit ich weis du ja Deutscher bist. 

Probier mal folgendes:

In der Home App den Rolladen vollständig öffnen.
Per Taster oder Shelly App auf einen Wert unter 50% fahren.
In der HomeApp wird lange zeit ein öffnen angezeigt und manchmal wechselt es zu schließen.
Der Status ändert sich oft erst nach einer Ewigkeit. 

Ich schließe nicht aus, dass es am Aktor liegt. Ich hatte bereits ein Software Problem mit ihm, welches ich erst nach einer Stunde zusammen mit dem Chefentwickler der Firmware von Shelly lösen konnte.

Bezüglich des mqtt log, welchen Befehl benutze ich am besten für einen mosquito server, damit alle erforderlichen Werte angezeigt werden. Ich benutze häufig nur zum überprüfen den sudo mosquitto_sub -t shellies/ usw.

**Comment by knstntn1** [comment]
Hab es kurz nachgespielt, bei mir wird die manuell angefahrene Position sofort geupdated. Du kannst ruhig mit mosquitto_sub einfach den ganzen Traffic auf shellies/# mitschneiden. Ich nutze immer eine App (MQTTool) dafür, daraus kann man aber nicht exportieren.

**Comment by rpolenthon** [comment]
Danke für deine Bereitschaft. Es hat sich wohl erledigt. Es liegt entweder am Shelly selbst oder der schlechten WLAN Abdeckung im Keller. Es handelt sich nämlich um ein Kellerfenster. Möglicherweise ist auch der Repeater das Problem. Der Shelly ist in etwa genau zwischen Fritzbox und Repeater. Ich werde das beobachten. Sollte ich bei anderen Fenstern die die Tage umgerüstet werden erneut Probleme haben, melde ich mich nochmal. Aber bis dahin vielen Dank für dieses Plugin!

Da wäre noch etwas. Ich bin Entwickler der IOS App "Homemanager".  Diese ist in erster Linie für das Einrichten und Verwalten von Homebridge. Jedoch anderes als bisherige Anbieter, hust hust... Der Nutzer kann Installationsparameter graphisch und erklärt ändern, es gibt Instanzen Support, smarte config example Erkennung zum einfachen graphischen bearbeiten, und vieles mehr. Jetzt zum Thema warum ich das erzähle. Es sollen nach und nach viele Plugins als "supported" hinzugefügt werden. Diese sind dann in der jeweiligen Sprache beschrieben und die einzelnen Einstellungen lassen sich einfach eingeben und sind erklärt. Zukünftig ist ein Projekte Tab geplant, in dem man Projekte als Anregungen entnehmen kann. Diese führen einen dann z.b von der Einrichtung der Shellys zum automatisierten installieren der Plugins über das eingeben des Shelly Codes und der Einbindung in HomeKit.

Ich würde dich dabei gerne fragen, ob du sozusagen "Plugin Developer partner" wirst? Damit wird dein Name angezeigt und dein Plugin unter supported angezeigt, sowie in Anleitungen verwendet. Die Github Seite wird selbstverständlich ebenfalls verlinkt. Im Gegenzug wäre es wünschenswert, wenn du mir in einer kurzen Email mitteilst, wenn es ein Update mit größeren Änderungen gibt oder bei allgemein größer auftretenden Problemen (diese werden in der Datenbank hinterlegt und alle Nutzer sehen, dass sie bei einem Problem nicht die einzigen sind).

Ich bin bereits in Kontakt mit dem Homebridge Entwickler, welcher das ganze Projekt selbst sehr interessant findet. Im Sommer sind unteranderem auch Entwickler Features geplant, aus "Spionage Gründen" kann ich dazu nur privat per email Auskünfte geben.

Aktuell sind wir noch im späten Entwicklungsstadium, der erste Beta Test unter Entwicklern startet voraussichtlich Anfang-Mitte Februar.

Ich würde mich über eine Email an press@homemanager-app.de freuen.

Gruß
Ron Polenthon

**Comment by knstntn1** [comment]
Hi Ron, i will contact you. Are there any news about the initial issue?

**Comment by rpolenthon** [comment]
Hi,
nice to hear. After setting a static IP for the Shelly it works as aspected, but with a little delay. At weekend I changed also two another blades from homematic to shelly, same little delay. The problem does only appear when the state is between closed and opened. Between them it often needs another message, which is send by the shelly every 30s by default. But I think that's ok. I will check this the next weeks also on my test pi for the app. For now I will close the issue.

Have a nice day!
