### ISSUE TITLE
mqttPositionStateValues - "DECREASEING_STATE", "INCREASING_STATE"

### ISSUE THREAD

**Issue by Kepete** [knstntn1/homebridge-mqtt-blinds#9]
1) I'm building currently my blinds and everything works fine, but I do not understand what for mqttPositionStateValues "DECREASEING_STATE", "INCREASING_STATE" are ? 

I understand that the "STOPPED_STATE" needs to be received to change the state of opening... and closing... but what for the other two values? opening... and closing... are anyways displayed when a new % value is received. 

Thanks for the awesome plugin.

**Comment by knstntn1** [comment]
I have in mind, that these values aren‘t really necessary for the native Home App which calculates this Information with the current and target position values. I am not sure how other Apps handle this. But you are right, for now this isn‘t really necessary.

**Comment by Kepete** [comment]
Alright, forgot that it might be used with other programs also, not only Apples home :)
